import Head from 'next/head'
 import Image from 'next/image'
 import styles from '../../styles/Home.module.css'
 import Nav from 'react-bootstrap/Nav';
import NavDropdown from 'react-bootstrap/NavDropdown';
import Carousel from 'react-bootstrap/Carousel';

 import 'bootstrap/dist/css/bootstrap.min.css'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.h1}> WELCOME TO CARBIKE 360 </h1>
      <Nav
      activeKey="/home"
      onSelect={(selectedKey) => alert(`selected ${selectedKey}`)}
    >
      <Nav.Item>
        <Nav.Link href="/home">Active</Nav.Link>
      </Nav.Item>
      <Nav.Item>
        <Nav.Link eventKey="link-1">Link</Nav.Link>
      </Nav.Item>
      <Nav.Item>
        <Nav.Link eventKey="link-2">Link</Nav.Link>
      </Nav.Item>
      <Nav.Item>
        <Nav.Link eventKey="disabled" disabled>
          Disabled
        </Nav.Link>
      </Nav.Item>
    </Nav>


    <Carousel fade>
      <Carousel.Item>
        <Image
          className="d-block w-100"
          src="/img7.webp" layout="responsive" width="100" height="50" 
          alt="First slide"
        />
        <Carousel.Caption>
        <div className={styles.cards}>
        <h2> <marquee>FEEL THE SPEED LIKE NEVER BEFORE</marquee></h2>
              </div>
        </Carousel.Caption>
        
      </Carousel.Item>
      <Carousel.Item>
      <Image
          className="d-block w-100"
          src="/img10.jpg" layout="responsive" width="100" height="50" 
          alt="First slide"
        />
 <Carousel.Caption>
        <div className={styles.cards}>
        <h2> <marquee>FEEL THE SPEED LIKE NEVER BEFORE</marquee></h2>
              </div>
        </Carousel.Caption>
        
        
      </Carousel.Item>
      <Carousel.Item>
      <Image
          className="d-block w-100"
          src="/img11.webp" layout="responsive" width="100" height="50" 
          alt="First slide"
        />
 <Carousel.Caption>
        <div className={styles.cards}>
        <h2> <marquee>FEEL THE SPEED LIKE NEVER BEFORE</marquee></h2>
              </div>
        </Carousel.Caption>
        

       
      </Carousel.Item>
      <Carousel.Item>
      <Image
          className="d-block w-100"
          src="/img8.jpg" layout="responsive" width="100" height="50" 
          alt="First slide"
        /> <Carousel.Caption>
        <div className={styles.cards}>
        <h2> <marquee>FEEL THE SPEED LIKE NEVER BEFORE</marquee></h2>
              </div>
        </Carousel.Caption>
        

        
      </Carousel.Item>
      <Carousel.Item>
      <Image
          className="d-block w-100"
          src="/img12.jpg" layout="responsive" width="100" height="50" 
          alt="First slide"
        /> <Carousel.Caption>
        <div className={styles.cards}>
        <h2 > <marquee>FEEL THE SPEED LIKE NEVER BEFORE</marquee></h2>
              </div>
        </Carousel.Caption>
        

        
      </Carousel.Item>
    </Carousel>
      

      <main className={styles.main}>
        <h1 className={styles.title}>
          INDIA'S BEST CARS AVAILABLE...
        
        </h1>

        

        <div className={styles.grid}>
          <div className={styles.card}>
            <Image src="/img4.webp" width="200" height="180px" />
          <h1>Scorpio</h1>
          <p>Automatic</p>
          <h4>RS 20 lakhs onwards</h4>


            <div className={styles.details}>
              <a href="/cars/scorpio">View details</a>
            </div>
            </div>
            <div className={styles.card}>
            <Image src="/img2.webp" width="200" height="180px" />
            <h2>Forturner</h2>
            <p>Manual</p>
            <h4>RS 25.00 lakhs onwards</h4>
            <div className={styles.details}>
              <a href="/cars/forturner">View details</a>
            </div>
            </div>
            <div className={styles.card}>
            <Image src="/img1.webp"  width="200" height="180px" />
            <h2>Renault joe</h2>
            <p>Automatic</p>
            <h4>RS 8.00 lakhs onwards</h4>
            <div className={styles.details}>
              <a href="/cars/renaultjoe">View details</a>
            </div>
            </div>
            <div className={styles.card}>
            <Image src="/img13.jpg"  width="200" height="180px" />
            <h2>Citroen C3</h2>
            <p>Manual</p>
            <h4>RS 5.71 lakhs onwards</h4>
            <div className={styles.details}>
              <a href="/cars/citroen">View details</a>
            </div>
            </div>
            <div className={styles.card}>
            <Image src="/img3.webp" width="200" height="180px" />
            <h2>Tata Curvv</h2>
            <p>Automatic</p>
            <h4>RS 20.00 lakhs onwards</h4>
            <div className={styles.details}>
              <a href="/cars/tatacurvv">View details</a>
            </div>
            </div>
            </div>
            </main>
            </div>
  )
}